name: Release Velocity

on:
  push:
    tags:
      - 'velocity/v*.*.*'

jobs:
  release:
    uses: ./.github/workflows/_release.yaml
    permissions:
      contents: write
    with:
      platform: velocity
      modrinth-game-versions: |-
        1.21.x
        26.1.x
        26.2.x
    secrets: inherit
